name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [ '7.4' ]
#        php-versions: [ '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0' ]
        phpunit-versions: ['7.5.20']
#        include:
#          - php: '8.1'
#            phpunit-versions: ['7.5.20']
            
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
          tools: php-cs-fixer, phpunit:${{ matrix.phpunit-versions }}

      - name: Check PHP Version
        run: php -v

#      - name: Install PHPUnit
#        uses: php-actions/phpunit@v2

      - name: Check PHPUnit version
        run: phpunit --version

      - name: Start MySQL server
        run: sudo service mysql start

      - name: Prepare test database
        run: |
          export MYQSL_HOST=127.0.0.1
          export MYSQL_TCP_PORT=${{ job.services.mysql.ports['3306'] }}
          mysql -e 'CREATE DATABASE IF NOT EXISTS wordpress;' -uroot -proot
          
      - name: Install WordPress test database
        run: bash bin/install-tests-db.sh

      - name: Install WordPress test suite
        run: bash bin/install-tests.sh

      - name: Execute PhpUnit tests
        if: ${{ matrix.php >= 7.1 }}
        run: phpunit
