name: PHPUnit

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 8.1
            phpunit: 7.5.20
          - php: 8.0
            phpunit: 7.5.20
          - php: 7.4
            phpunit: 7.5.20
          - php: 7.3
            phpunit: 7.5.20
          - php: 7.1
            phpunit: 7.5.20
          - php: 7.0
            phpunit: 5.0
          - php: 5.6
            phpunit: 5.0

    name: PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpunit:${{ matrix.phpunit }}

      - name: Start MySQL service
        run: sudo /etc/init.d/mysql start

      - name: Switch to use mysql_native_password for PHP < 7.4
        if: ${{ matrix.php < 7.4 }}
        # Info https://www.php.net/manual/en/mysqli.requirements.php
        run: mysql -u root -p"root" -e "ALTER USER 'root'@localhost IDENTIFIED WITH mysql_native_password BY 'root'";  
               
      - name: Install WordPress environment
        run: bash bin/install-wp-tests.sh wordpress_tests root root

      - name: Execute PHPUnit tests
        if: ${{ matrix.php >= 7.1 }}
        run: phpunit
