name: CI

on: [push]

env:
  WP_TESTS_DIR: /github/home/wp-tests/wordpress-tests-lib
  WP_CORE_DIR: /github/home/wp-tests/wordpress

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [ '7.4' ]
#        php-versions: [ '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0' ]
        wordpress-version: [ latest ]
        phpunit-versions: ['7.5.20']
#        include:
#          - php: '8.1'
#            phpunit-versions: ['7.5.20']
    services:
      mysql:
        image: mysql:5.7.27
        env:
          MYSQL_ROOT_PASSWORD: root
            
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
          tools: php-cs-fixer, phpunit:${{ matrix.phpunit-versions }}

      - name: Check PHP Version
        run: php -v

#      - name: Install PHPUnit
#        uses: php-actions/phpunit@v2

      - name: Check PHPUnit version
        run: phpunit --version

      - name: Install WordPress test suite
        run: bash bin/install-wp-tests.sh wordpress_test root root mysql ${{ matrix.wordpress-version }}

      - name: Execute PhpUnit tests
        if: ${{ matrix.php >= 7.1 }}
        run: phpunit
