name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: 7.4
            wordpress: master
            phpunit: 7.5.20
#          - php: 7.3
#            wordpress: master
#            phpunit: 6.5.14
#          - php: 7.1
#            wordpress: master
#            phpunit: 6.5.14
#          - php: 7.0.33
#            wordpress: 4.9
#            phpunit: 6.5.14
#          - php: 5.6.20
#            wordpress: 4.7
#            phpunit: 5.7.27

    name: PHP ${{ matrix.php }} tests in WP ${{ matrix.wordpress }}
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpunit:${{ matrix.phpunit }}

      - name: Install WordPress environment
        run: |
          export WP_DEVELOP_DIR=/tmp/wordpress-tests-lib/
          git clone --depth=50 --branch="${{ matrix.wordpress }}" git://develop.git.wordpress.org/ /tmp/wordpress-tests-lib
          cd ..
          cp -r "${GITHUB_REPOSITORY#*/}" "/tmp/wordpress-tests-lib/src/wp-content/plugins/co-authors-plus"
          cd /tmp/wordpress-tests-lib/
          pwd
          cp wp-tests-config-sample.php wp-tests-config.php
          sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
          sed -i "s/yourusernamehere/root/" wp-tests-config.php
          sed -i "s/yourpasswordhere/root/" wp-tests-config.php

      - name: Create MySQL database
        run: |
          sudo /etc/init.d/mysql start
          mysql -u root -proot -e "CREATE DATABASE wordpress_tests;"

      - name: Execute PHPUnit tests
        run: |
          cd "/tmp/wordpress-tests-lib/src/wp-content/plugins/co-authors-plus"
          pwd
          phpunit
