name: PHPUnit

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.0', '7.4', '7.3', '7.2', '7.1', '7.0', '5.6' ]
        wordpress: [ '5.7', '5.6', '5.5' ]

    name: WordPress ${{ matrix.wordpress }} with PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpunit:7.5.20

      - name: Start MySQL service
        run: sudo /etc/init.d/mysql start

      - name: Switch to use mysql_native_password for PHP < 7.4
        if: ${{ matrix.php < 7.4 }}
        # Info https://www.php.net/manual/en/mysqli.requirements.php
        run: mysql -u root -p"root" -e "ALTER USER 'root'@localhost IDENTIFIED WITH mysql_native_password BY 'root'";  
               
      - name: Install WordPress environment
        run: bash bin/install-wp-tests.sh wordpress_tests root root localhost ${{ matrix.wordpress }}

      - name: Execute PHPUnit tests
        if: ${{ matrix.php >= 7.1 }}
        run: phpunit
