name: Integration

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: phpunit

      - name: Setup WordPress environment for tests
        run: bash bin/install-wp-tests.sh wordpress_test root root localhost latest
        
      - name: Run PHPUnit tests
        uses: php-actions/phpunit@v2
        with:
          version: '7.5.20'
          php_version: '7.4'
